
// 会员列表
export const LOAD_MEMBERLIST = {
	INIT: 'LOAD_MEMBERLIST_INIT',
	SUCCESS: 'LOAD_MEMBERLIST_SUCCESS',
	ERROR: 'LOAD_MEMBERLIST_ERROR',
}

// 常旅列表
export const LOAD_TRAVELLERLIST = {
	INIT: 'LOAD_TRAVELLERLIST_INIT',
	SUCCESS: 'LOAD_TRAVELLERLIST_SUCCESS',
	ERROR: 'LOAD_TRAVELLERLIST_ERROR',
}